version: '3'

services:
  app:
    build:
      context: ./app
    volumes:
      - ../:/var/www:cached
      - ./app/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./app/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./app/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "${APP_PORT}:80"
      - "${XDEBUG_PORT}:9003"
    depends_on:
      - postgres
      - redis
      - mailhog
    networks:
      - app
  postgres:
    build:
      context: ./postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
    networks:
      - app
  redis:
    build: ./redis
    volumes:
      - ./.data/redis:/data
    command: --requirepass secret
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app
  mailhog:
    build: ./mailhog
    ports:
      - "${MAILHOG_PORT}:1025"
      - "${MAILHOG_WEB_PORT}:8025"
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres:
    driver: local
  redis:
    driver: local
