name: php.test

on:
  pull_request:
    branches: [master, develop]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, redis, bcmath
          tools: composer:v2
          coverage: pcov

      - name: Composer Validate
        run: composer validate

      - name: Install Dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      - name: Prepare Application Environment
        run: |
          echo 'DB_HOST=localhost' >> .env.testing
          echo 'DB_PORT=5432' >> .env.testing
          echo 'DB_DATABASE=test' >> .env.testing
          echo 'DB_USERNAME=root' >> .env.testing
          echo 'DB_PASSWORD=root' >> .env.testing

      - name: Run Tests
        run: composer run-script test
